Fastfood/Areas/Admin/Controllers/CategoryController.cs
using Fastfood.Data;
using Fastfood.Models;
using Fastfood.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fastfood.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _db.Categories.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if(ModelState.IsValid)
            {
                _db.Categories.Add(category);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _db.Categories.FindAsync(id);

            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if(ModelState.IsValid)
            {
                _db.Update(category);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(category);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _db.Categories.FindAsync(id);

            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _db.Categories.FindAsync(id);

            if (category == null)
                return NotFound();

            _db.Categories.Remove(category);
            await _db.SaveChangesAsync();


            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _db.Categories.FindAsync(id);

            if (category == null)
                return NotFound();

            return View(category);
        }
    }
}

Fastfood/Areas/Admin/Controllers/CouponController.cs
using Fastfood.Data;
using Fastfood.Models;
using Fastfood.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Fastfood.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupons.ToListAsync());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupon)
        {
            if(ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;

                if(files.Count > 0)
                {
                    byte[] byteArray = null;
                    using(var fs1 = files[0].OpenReadStream())
                    {
                        using(var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            byteArray = ms1.ToArray();
                        }
                    }
                    coupon.Picture = byteArray;
                }

                _db.Coupons.Add(coupon);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(coupon);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var coupon = await _db.Coupons.FindAsync(id); ;

            if (coupon == null)
                return NotFound();

            return View(coupon);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon coupon)
        {
            if (coupon == null)
                return NotFound();

            var couponFromDb = await _db.Coupons.FirstOrDefaultAsync(woak => woak.Id == coupon.Id);

            if(ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;


                if (files.Count > 0)
                {
                    byte[] byteArray = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            byteArray = ms1.ToArray();
                        }
                    }
                    couponFromDb.Picture = byteArray;
                }
                couponFromDb.MiniAmount = coupon.MiniAmount;
                couponFromDb.Name = coupon.Name;
                couponFromDb.Discount = coupon.Discount;
                couponFromDb.Coupontype = coupon.Coupontype;
                couponFromDb.IsActive = coupon.IsActive;

                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(coupon);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var coupon = await _db.Coupons.FindAsync(id);

            if (coupon == null)
                return NotFound(0);

            return View(coupon);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var coupon = await _db.Coupons.FindAsync(id);

            if (coupon == null)
                return NotFound();

            return View(coupon);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var coupon = await _db.Coupons.SingleOrDefaultAsync(c => c.Id == id);

            _db.Coupons.Remove(coupon);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

Fastfood/Areas/Customer/Controllers/CartController.cs
using Fastfood.Data;
using Fastfood.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Fastfood.Utilities;
using Fastfood.Models;

namespace Fastfood.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public OrderDetailsCart detailCart { get; set; }

        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };
            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = _db.shoppingCarts.Where(c => c.ApplicationUserId == claim.Value);

            if (cart != null)
                detailCart.listCart = cart.ToList();

            foreach(var list in detailCart.listCart)
            {
                list.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(woak => woak.Id == list.MenuItemId);

                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);

                if (list.MenuItem.Description.Length > 100)
                    list.MenuItem.Description = list.MenuItem.Description.Substring(0, 99) + "...";
                    
            }

            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;

            if(HttpContext.Session.GetString(SD.ssCouponCode) != null)
            {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponDb = await _db.Coupons.Where(c => c.Name == detailCart.OrderHeader.CouponCode).FirstOrDefaultAsync();
                detailCart.OrderHeader.OrderTotal = SD.DiscountPrice(couponDb, detailCart.OrderHeader.OrderTotalOriginal);
            }

            return View(detailCart);
        }

        public async Task<IActionResult> Summary()
        {
            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };

            detailCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ApplicationUser applicationUser = await _db.ApplicationUsers.Where(c => c.Id == claim.Value).FirstOrDefaultAsync();

            var cart = _db.shoppingCarts.Where(c => c.ApplicationUserId == claim.Value);

            if (cart != null)
                detailCart.listCart = cart.ToList();

            foreach (var list in detailCart.listCart)
            {
                list.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(woak => woak.Id == list.MenuItemId);

                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);

            }

            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;
            detailCart.OrderHeader.PickupName = applicationUser.Name;
            detailCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            detailCart.OrderHeader.PickUpTime = DateTime.Now;

            if (HttpContext.Session.GetString(SD.ssCouponCode) != null)
            {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponDb = await _db.Coupons.Where(c => c.Name == detailCart.OrderHeader.CouponCode).FirstOrDefaultAsync();
                detailCart.OrderHeader.OrderTotal = SD.DiscountPrice(couponDb, detailCart.OrderHeader.OrderTotalOriginal);
            }

            return View(detailCart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            detailCart.listCart = await _db.shoppingCarts.Where(c => c.ApplicationUserId == claim.Value).ToListAsync();
            
            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailCart.OrderHeader.OrderDate = DateTime.Now;
            detailCart.OrderHeader.UserId = claim.Value;
            detailCart.OrderHeader.State = SD.PaymentStatusPending;
            detailCart.OrderHeader.PickUpTime = DateTime.Now.AddHours(2);


            List<OrderDetail> orderDetailList = new List<OrderDetail>();
            _db.OrderHeaders.Add(detailCart.OrderHeader);
            await _db.SaveChangesAsync();

            detailCart.OrderHeader.OrderTotalOriginal = 0;

            foreach (var item in detailCart.listCart)
            {
                item.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(m => m.Id == item.MenuItemId);

                OrderDetail orderDetails = new OrderDetail()
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = detailCart.OrderHeader.Id,
                    Description = item.MenuItem.Description,
                    Price =item.MenuItem.Price,
                    Count = item.Count
                    
                };
                detailCart.OrderHeader.OrderTotalOriginal += orderDetails.Count * orderDetails.Price;
                _db.OrderDetails.Add(orderDetails);
            }

            if(HttpContext.Session.GetString(SD.ssCouponCode) != null)
            {
                detailCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponFromDb = await _db.Coupons.Where(c => c.Name == detailCart.OrderHeader.CouponCode).FirstOrDefaultAsync();

                detailCart.OrderHeader.OrderTotal = SD.DiscountPrice(couponFromDb, detailCart.OrderHeader.OrderTotalOriginal);
            }
            else
            {
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotalOriginal;
            }
            detailCart.OrderHeader.CouponDiscount = detailCart.OrderHeader.OrderTotalOriginal - detailCart.OrderHeader.OrderTotal;

            _db.shoppingCarts.RemoveRange(detailCart.listCart);
            HttpContext.Session.SetInt32(SD.ssShopingCartCount, 0);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddCoupon()
        {
            if (detailCart.OrderHeader.CouponCode == null)
                detailCart.OrderHeader.CouponCode = string.Empty;
            HttpContext.Session.SetString(SD.ssCouponCode, detailCart.OrderHeader.CouponCode);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString(SD.ssCouponCode, string.Empty);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Plus(int cartId)
        {
            var cart = await _db.shoppingCarts.FirstOrDefaultAsync(c => c.Id == cartId);

            cart.Count += 1;
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Minus(int cartId)
        {
            var cart = await _db.shoppingCarts.FirstOrDefaultAsync(c => c.Id == cartId);

            if(cart.Count == 1)
            {
                _db.shoppingCarts.Remove(cart);
                await _db.SaveChangesAsync();

                var cnt = _db.shoppingCarts.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;

                HttpContext.Session.SetInt32(SD.ssShopingCartCount, cnt);
            }
            else
            {
                cart.Count -= 1;
                await _db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Remove(int cartId)
        {
            var cart = await _db.shoppingCarts.FirstOrDefaultAsync(c => c.Id == cartId);

            _db.shoppingCarts.Remove(cart);
            await _db.SaveChangesAsync();

            var cnt = _db.shoppingCarts.Where(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
            HttpContext.Session.SetInt32(SD.ssShopingCartCount, cnt);


            return RedirectToAction(nameof(Index));
        }
    }
}

Fastfood/Views/Shared/_CreateAndBackToListButton.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="درج" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">بازگشت</a>
    </div>
</div>

Fastfood/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info">جدید</a>
</p>

Fastfood/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="حذف" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">بازگشت</a>
    </div>
</div>

Fastfood/Views/Shared/_DetailAndBackToListButton.cshtml
@model int


<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">ویرایش</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">بازگشت</a>
    </div>
</div>

Fastfood/Views/Shared/_EditAndBackToListButton.cshtml
@model int

    <div class="row">

        <div class="col-6">
            <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="ذخیره" />
        </div>

        <div class="col-6">
            <a asp-action="Index" class="btn btn-success form-control">بازگشت</a>
        </div>
    </div>

Fastfood/Views/Shared/_IndividualOrderDetails.cshtml
@model Fastfood.Models.ViewModels.OrderDetailsViewModel
@using Fastfood.Utilities
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>نام</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label>کاربر</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label>تلفن</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label>مجموع</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>



        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">شناسه سفارش: </span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.OrderDetails)
                {
    <li class="list-group-item d-flex justify-content-between">
        <div>
            <small class="text-muted">تعداد : @details.Count</small>
        </div>
        <span class="text-muted">@(details.Price * details.Count)</span>
    </li>
}
                @if (Model.OrderHeader.CouponCode != null)
                {
    <li class="list-group-item d-flex justify-content-between">
        <div class="text-success">
            <small>@Model.OrderHeader.CouponCode</small>
        </div>
        <span class="text-success">@(Model.OrderHeader.OrderTotalOriginal - Model.OrderHeader.OrderTotal)</span>
    </li>
}
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info"> مجموع مبلغ</span>
                    <strong class="text-info">$@Model.OrderHeader.OrderTotal</strong>
                </li>

            </ul>
        </div>

    </div>
</form>

Fastfood/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Fastfood.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fastfood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-rtl.min.css" />
    <link href="~/lib/fontawesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/brands.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/solid.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">تهیه غذا</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                        </li>
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">پنل مدیریت</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">فهرست</a>

                                    <a class="dropdown-item" asp-area="Admin" asp-controller="SubCategory" asp-action="Index">زیرگروه</a>

                                    <a class="dropdown-item" asp-area="Admin" asp-controller="MenuItem" asp-action="Index">منو</a>

                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">کوپن</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser))

                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Order" asp-action="OrderHistory">
                                    تاریخچه سفارشات
                                </a>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShopingCartCount) != null)
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShopingCartCount);
                                    }
                                    <i class="fas fa-shopping-cart">&nbsp; (@count)</i>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#">
                                    <i class="fas fa-shopping-cart">&nbsp; (0)</i>
                                </a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Fastfood/Views/Shared/_StatusMessage.cshtml
@model string

@if(!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("خطا") ? "danger" : "success";

    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span>&times;</span>@Model</button>
    </div>
}

Fastfood/Views/Shared/_TableButtonPartial.cshtml
@model int


<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>

</td>

Fastfood/Views/Shared/_ThumbnailArialPartial.cshtml
@model IEnumerable<MenuItem>


@if(Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">

        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom: 10px; margin-top: 10px; padding:10px">
                <div class="row">


                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="90%" style="border-radius:5px;border:1px solid #bbb9b9" />
                    </div>


                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">
                                    @item.Name
                                </label>

                                @if (item.Spicyness == "1")
                                {
                                    <img src="/images/mild.png" title="sade" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img src="/images/spicy.png" title="spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img src="/images/verySpicy.png" title="veryspicy" />
                                }
                            </div>
                            <div class="col-4">
                                <h4>@item.Price</h4>
                            </div>
                        </div>
                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@item.Description</p>
                        </div>

                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">
                                سفارش
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4"></div>
    </div>
}